"""Formatting modes and prompt preset engine for Scribe Dictation."""

from scribe_dictation.formatters.modes import (
    FormattingMode,
    FormatEngine,
    RAW_MODE,
    CLEAN_MODE,
    BULLETS_MODE,
    MEETING_NOTES_MODE,
    EMAIL_MODE,
    CODE_COMMENT_MODE,
    SUMMARY_MODE,
    TRANSLATE_EN_MODE,
    BUILTIN_MODES,
    TRANSFORM_MODES,
    get_mode_by_id,
    clean_filler_words,
    clean_stutters,
    clean_numbers,
    clean_punctuation_and_capitalization,
)
from scribe_dictation.formatters.app_profiler import (
    AppProfile,
    AppProfileManager,
    DEFAULT_APP_PROFILES,
    detect_active_window,
    SETTINGS_APP_PROFILES,
    SETTINGS_PROFILES_ENABLED,
    SETTINGS_PROFILES_FALLBACK,
)
from scribe_dictation.formatters.verbal_commands import (
    VerbalCommandParser,
    parse_verbal_commands,
    SETTINGS_VERBAL_COMMANDS_ENABLED,
)
from scribe_dictation.formatters.snippets import (
    VoiceSnippet,
    VoiceSnippetManager,
    expand_variables,
    DEFAULT_VOICE_SNIPPETS,
    SETTINGS_SNIPPETS_CONFIG,
    SETTINGS_SNIPPETS_ENABLED,
)

__all__ = [
    "FormattingMode",
    "FormatEngine",
    "RAW_MODE",
    "CLEAN_MODE",
    "BULLETS_MODE",
    "MEETING_NOTES_MODE",
    "EMAIL_MODE",
    "CODE_COMMENT_MODE",
    "SUMMARY_MODE",
    "TRANSLATE_EN_MODE",
    "BUILTIN_MODES",
    "TRANSFORM_MODES",
    "get_mode_by_id",
    "clean_filler_words",
    "clean_stutters",
    "clean_numbers",
    "clean_punctuation_and_capitalization",
    "AppProfile",
    "AppProfileManager",
    "DEFAULT_APP_PROFILES",
    "detect_active_window",
    "SETTINGS_APP_PROFILES",
    "SETTINGS_PROFILES_ENABLED",
    "SETTINGS_PROFILES_FALLBACK",
    "VerbalCommandParser",
    "parse_verbal_commands",
    "SETTINGS_VERBAL_COMMANDS_ENABLED",
    "VoiceSnippet",
    "VoiceSnippetManager",
    "expand_variables",
    "DEFAULT_VOICE_SNIPPETS",
    "SETTINGS_SNIPPETS_CONFIG",
    "SETTINGS_SNIPPETS_ENABLED",
]
